### ISSUE TITLE
你好，项目直接npm start可运行吗 

### ISSUE THREAD

**Issue by limit123123** [niuxiangchen/React-online-retailers-client#1]
你好，项目直接npm start可运行吗

**Comment by niuxiangchen** [comment]
你还需要拉取下[服务端的代码](https://github.com/niuxiangchen/React-Admin-BE)，还有配置下数据库的文件，你可以去尚硅谷的[网课](https://www.bilibili.com/video/BV1i4411N7Qc)评论区看看找一下数据库的sql文件
